config/routes.rb
WebProject::Application.routes.draw do
  

  get "comment/create"

  devise_for :users 
  resources :questions, only: [:create, :destroy] do
   member do
     post 'upvote'
     post 'downvote'
     post 'accept'
   end
  end
  resources :answers, only: [:create, :destroy]
  
  resources :comments, only: [:create, :destroy]

  root :to => "static_pages#home"

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact' 
  match '/profile', to: 'users#show'
  match '/users', to: 'users#index'
  match '/users/:id', :to => 'users#destroy', :as => :user
  match '/users/:id/edit', :to => 'users#edit' , :as => :edit_user
  match '/questions/:id', :to => 'questions#reply'
  match '/questions/:id', :to => 'questions#destroy', :as => :question_destroy
  match '/questions/:id/upvote', :to => 'questions#upvote', :as => :question_upvote
  match '/questions/:id/downvote', :to => 'questions#downvote', :as => :question_downvote
  match '/questions/:id/accept', :to => 'questions#accept', :as => :question_accept
  
  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
  end 
  
  devise_scope :user do
    get "sign_up", :to => "devise/registrations#new"
  end 

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :correct, :question_id, :user_id, :vote, :answer_id
  belongs_to :question
  belongs_to :user
  has_many :comment, dependent: :destroy
  validates :user_id, presence: true
  acts_as_votable
  
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :answer_id, :content
  belongs_to :answer
  validates :answer_id, presence: true
end

app/models/pregunta.rb
class Pregunta < ActiveRecord::Base
  attr_accessible  :content, :tags
  belongs_to :user 
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 500 }
  default_scope order: 'pregunta.created_at DESC'
end

app/models/question.rb
class Question < ActiveRecord::Base
    attr_accessible  :content, :tags, :id
    belongs_to :user 
    has_many :answer, dependent: :destroy
    validates :user_id, presence: true
    validates :content, presence: true, length: { maximum: 500 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :admin
  # attr_accessible :title, :body
  has_many :question, dependent: :destroy
  has_many :answer, dependent: :destroy
  acts_as_voter
  
  def feed
    Question
  end
  
  def feea
    Answer
  end
  
  def feec
    Comment
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :authenticate_user!
  
  def create
   @feed_items = User.first.feea.paginate(page: params[:page]) 
    @answer = current_user.answer.build(params[:answer])
    if @answer.save
    flash[:success] = "Respuesta Enviada!"
      redirect_to :back
    else
    flash[:success] = "Respuesta No Enviada!"
      render 'static_pages/home'
    end
  end

  def destroy
    Answer.find(params[:id]).destroy
    flash[:success] = "Answer destroyed."
    redirect_to root_url
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
 
    @comment = Comment.new(params[:comment])

    if @comment.save
    flash[:success] = "Comentario Agregado!"
      redirect_to :back
    else
      render 'static_pages/home'
    end

  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
  end
  
  def reply
    @feed_items = User.first.feea.paginate(page: params[:page]) 
    @question = Question.find(params[:id])
    @user = current_user
    @answer = @user.answer.paginate(page: params[:page])
    @quest = current_user.answer.build if user_signed_in?
    @comment_list= Comment.all
    @cont = Comment.new if user_signed_in?
  end
  
  def create
  @question = current_user.question.build(params[:question])
    if @question.save
      flash[:success] = "Pregunta Creada!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    flash[:success] = "Question destroyed."
    redirect_to root_url
  end
  
  def accept
  
  flash[:success] = "Ha aceptado una respuesta!"
    @answer = Answer.find(params[:id])
    @answer.correct = true
    @answer.save
    @question = Question.find(params[:format])
    @question.answered = true
    @question.save
    redirect_to :back
  end
  
  def upvote
  flash[:success] = "Ha votado por una respuesta!"
    @answer = Answer.find(params[:id])
    @answer.liked_by current_user
    @answer.save
    redirect_to :back
  end
  
  def downvote
  flash[:success] = "Ha votado por una respuesta!"
    @answer = Answer.find(params[:id])
    @answer.downvote_from current_user
    @answer.save
    redirect_to :back
  end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
   @question = Question 
   if not User.first.nil?
      @feed_items = User.first.feed.paginate(page: params[:page]) 
   else
      @feed_items = []
   end
  end

  def help
  end
  
  def about
  end
  
  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!
before_filter :admin_user, only: :destroy
  def show
    #@user = User.find(params[:id])
    @user = current_user
    @question = @user.question.paginate(page: params[:page])
    @quest = current_user.question.build if user_signed_in?
  
  end
  
  def index
		@users = User.paginate(page: params[:page])

  end
  
  def edit
    @user = current_user
  end
  
  def destroy
  @destroy_user = User.find(params[:id])
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end


  private
 
    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
    
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

# Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Cool Message Board"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
  
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

def gravatar_for(user, options = { size: 50 })
  gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
  size = options[:size]
  gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  image_tag(gravatar_url, alt: user.email, class: "gravatar")
end
  
end

app/views/comment/create.html.erb
<h1>Comment#create</h1>
<p>Find me in app/views/comment/create.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Cool Message Board
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "CMB", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>
            <% if user_signed_in? %>
           
            <% if current_user.admin? %>
          <li><%= link_to "Users",    users_path %></li>
          <% else %>
            <li><%= link_to "Profile",    profile_path %></li>
           <% end %>
           <li>
          <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
          </li>
        <% else %>
          <li>
          <li><%= link_to "Sign in", sign_in_path %></li>
          </li>
        <% end %>
          
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/questions/_downvote.html.erb
<%= form_for(feed_answer.upvote current_user) do |f| %>
  <%= f.submit "Upvote", class: "btn btn-large btn-primary" %>
<% end %>

app/views/questions/_question.html.erb
<li>
  <span class="content"><%= question.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(question.created_at) %> ago.
  </span>
</li>

app/views/questions/_questions.html.erb
<li>
  <span class="content"><%= question.content %></span>
  <br><br>
  <span class="timestamp">
    Posted <%= time_ago_in_words(question.created_at) %> ago.
  </span>
</li>

app/views/questions/_upvote.html.erb
<%= form_for(@feed_answer.liked_by current_user) do |f| %>
  <%= f.submit "Upvote", class: "btn btn-large btn-primary" %>
<% end %>

app/views/questions/reply.html.erb
<br><br>
<li>

  <span class="content"><%= @question.content %></span>

  <span class="timestamp">
    Posted <%= time_ago_in_words(@question.created_at) %> ago.
  </span>
  <br><br>
  <% if @question.user.id != current_user.id %>
    <section>
        <%= render 'shared/answer_form' %>
  </section>
  <% end %>
  
  <h3>Lista de Respuestas</h3>
  <%= render 'shared/feea' %>
</li>

app/views/shared/_answer_form.html.erb
<%= form_for(@quest) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Escriba una respuesta..." %>
    <%= f.hidden_field :question_id, :value => @question.id %>
  </div>


  <%= f.submit "Responder", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_error_messages.html .erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Contiene <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feea.html.erb
<% if @feed_items.any? %>
  <ol class="questions">
    <%= render partial: 'shared/feed_answer', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <%= will_paginate @feed_items %>
  <ol class="questions">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>

<% end %>

app/views/shared/_feed_answer.html.erb
<% if feed_answer.question_id == @question.id %>

<li id="<%= feed_answer.id %>">


  <%= link_to gravatar_for(feed_answer.user), feed_answer.user %>
  <span class="user">
    <%= link_to feed_answer.user.email, feed_answer.user %>
  </span>
  <span class="content"><%= feed_answer.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_answer.created_at) %> ago.
  </span>
  <% if user_signed_in? %>
  <% if !@question.answered? %>
      <% if @question.user_id == current_user.id %>
         <%= link_to 'Accept Answer', accept_question_path(feed_answer.id, @question.id )%>
      <% end %>
    <% end %>
       <% if !current_user.voted_down_on? feed_answer %>
        <% if !current_user.voted_up_on? feed_answer %>
              <% if feed_answer.user.id != current_user.id %>
         <%= link_to 'Upvote', upvote_question_path(feed_answer.id) %>
         <% end %>
          <% end %>
        <% end %>
  <% end %>
  <%= feed_answer.upvotes.size %><img alt="Upvotes" src="/assets/upvote.png" height="42" width="42" />

  <% if user_signed_in? %>
    <% if !current_user.voted_down_on? feed_answer %>
        <% if !current_user.voted_up_on? feed_answer %>
              <% if feed_answer.user.id != current_user.id %>
         <%= link_to 'Downvote', downvote_question_path(feed_answer.id) %>
              <% end %>
        <% end %>
      <% end %>
  <% end %>

  <%= feed_answer.downvotes.size %><img alt="Downvotes" src="/assets/downvote.png" height="42" width="42" />

  <% if feed_answer.correct? %>
     <img alt="Accept" src="/assets/check.png" height="42" width="42" />
      Respuesta Aceptada

  <% end %>

  <h6>Comentarios</h6>

  <% @comment_list.each do |o| %>
    <% if o.answer_id == feed_answer.id %>
      <span class="content"><%= o.content  %></span>
      <br>
    <% end %>
  <% end %>

    <% if user_signed_in? %>

      <%= form_for(@cont) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.text_area :content, placeholder: "Comentario nuevo..." , :size => "30x2"%>
        <%= f.hidden_field :answer_id, :value => feed_answer.id %>
      </div>

      <%= f.submit "Comentar", class: "btn btn-large btn-primary" %>
    <% end %>

 <% end %>
</li>

 <% end %>

app/views/shared/_feed_com.html.erb
<li id="<%= feed_com.id %>">


    <span class="content"><%= feed_com.content %></span>


</li>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.email, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
  <% if user_signed_in? %>
      <% if current_user.admin? %>
           <%= link_to "delete question", feed_item, method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% else %>
           <%= link_to "See Question", feed_item, method: :reply %>
      <% end %>
      
  <% end %>
 <% if feed_item.answered? %>
     <img alt="Accept" src="/assets/check.png" height="42" width="42" />
      Pregunta Contestada
      
  <% end %>
  

</li>

app/views/shared/_micropost_form.html .erb
<%= form_for(@question) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Escriba una nueva Pregunta..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_question_form.html.erb
<%= form_for(@quest) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Escriba una nueva Pregunta..." %>
  </div>
  <%= f.submit "Preguntar", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.email %>
</h1>
<span>
<%= link_to "Editar mi perfil", edit_user_path(current_user.id)  %>
  

</span>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>Sobre Nosotros</h1>
<p>
  Jesus Osorio.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contacto</h1>
<p>
  Puede contactarnos en el siguiente enlace <a href="https://twitter.com/Klaus_omgwtf">Jesus Osorio</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  En esta pagina puede realizar preguntas sobre cualquier tema.
  Luego podra recibir respuestas, aceptarlas, comentarlas y darles un voto.
  Para ver ejemplos de paginas similares, visite
  <a href="http://stackoverflow.com/">stackoverflow.com</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Bienvenido a Cool Message Board</h1>

  <h2>
    Aqui podras encontrar la respuesta a todas tus preguntas.

  </h2>


</div>

<% if signed_in? %>




<% else %>

    

<div class="center">
 <iframe width="560" height="315" src="http://www.youtube.com/embed/NWHfY_lvKIQ" frameborder="0" allowfullscreen></iframe>
   <br>
    <br>
    <%= link_to "Sign up now!", sign_up_path, class: "btn btn-large btn-primary" %>
</div>

<% end %> 

<h3>Lista de Preguntas</h3>

    <%= render 'shared/feed' %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %> 
<h1>Update your profile</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>


      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>
    <br>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

    <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<%= will_paginate %>
<ul class="users">
  <% @users.each do |user| %>
	<%if user.id != current_user.id %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= user.email %>
      <%= link_to "delete user", user, :method => :destroy, :confirm => "You sure?" %>
<br>
<br>
<br>
<br>
    </li>
	<% end %>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="row">

  <div class="row">
    <aside class="span4">
        <%= render 'shared/user_info' %>
        <br>
        <br>
       <section>
        <%= render 'shared/question_form' %>
      </section>
    </aside>
  </div>

  <div class="span8">
    <% if @user.question.any? %>
      <h3>Preguntas (<%= @user.question.count %>)</h3>
        <%= will_paginate @question %>
      <ol class="questions">
        <%= render @question %>
      </ol>
   <% end %>
    <%= will_paginate @question %>
  </div>
</div>